# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  glossary_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  glossary_web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@glossary_postgres:${POSTGRES_PORT}/${POSTGRES_DB}
        API_KEY: ${API_KEY}
    ports:
      - "8000:8000"
    command: ["uvicorn", "dds_glossary.main:app", "--host", "0.0.0.0"]
    depends_on:
      glossary_postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/version"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
