name: Python 🐍 Deploy 🚀

on:
  workflow_run:
    workflows: ["python-test"]
    types:
    - completed
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  deploy:
    name: Deoploy to server 🚀
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH Directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Setup SSH Known Hosts
      run: |
        ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        rsync -vr --delete ${GITHUB_WORKSPACE} ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SSH_USER }}/sites/

    - name: Compose up services
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
        export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        export API_KEY=${{ secrets.API_KEY }}
        cd /home/${{ secrets.SSH_USER }}/sites/dds_glossary/
        docker compose -f compose.yaml up glossary_postgres glossary_web --build -d
        EOF
