name: Python 🐍 Deploy 🚀

on:
  workflow_run:
    workflows: ["python-test"]
    types:
    - completed
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  deploy:
    name: Deoploy to server 🚀
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH Directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Setup SSH Known Hosts
      run: |
        ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        rsync -v --delete ${GITHUB_WORKSPACE} ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SSH_USER }}/sites/

    - name: Deploy to Server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /home/${{ secrets.SSH_USER }}/sites/
        docker compose restart postgres glossary_web
        EOF
