name: Python 🐍 Deploy 🚀

on:
  workflow_run:
    workflows: ["python-test"]
    types:
    - completed
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  deploy:
    name: Deoploy to server 🚀
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        scp -r . ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SSH_USER }}/sites/

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /home/${{ secrets.SSH_USER }}/sites/
        docker compose restart postgres glossary_web
        EOF
